version: "3.9"

services:
  postgres-test:
    image: postgres
    container_name: postgres-test
    restart: always
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-test
    ports:
      - "5432:5432"
  postgres-test-migrations:
    image: migrate/migrate
    container_name: postgres-test-migrations
    restart: on-failure
    depends_on:
      - postgres-test
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./migrations:/migrations
    entrypoint: []
    command: /wait-for-it.sh postgres-test:5432 -- migrate -path=/migrations/ -database postgres://postgres:postgres@postgres-test:5432/postgres-test?sslmode=disable up